version: "3.8"

services:
  monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: monitor-service
    volumes:
      - logs:/var/log  # Shared volume for logs
    restart: always

  api:
    build:
      context: ./python-api 
      dockerfile: ../docker/Dockerfile.api  # Use the correct API Dockerfile
    container_name: api-service
    ports:
      - "8000:8000"  # Expose API to host machine
    depends_on:
      - monitor
    volumes:
      - logs:/var/log  # Shared volume for logs
    restart: always

volumes:
  logs:
