version: "3.8"

services:
  monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: monitor-service
    volumes:
      - logs:/var/log  # Shared volume for logs
    restart: always

  api:
    build:
      context: .  # build context is the project root
      dockerfile: docker/Dockerfile.api  # ensure this path is correct relative to project root
    container_name: api-service
    ports:
      - "8000:8000"
    depends_on:
      - monitor
    volumes:
      - logs:/var/log
    restart: always
    
volumes:
  logs:
