# Use official Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy and install dependencies
COPY python-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY python-api/ .

# Command to run FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]