name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push FastAPI Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.api  # Correct Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/python-api:latest

      - name: Build and Push Monitor Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile  # Correct Dockerfile path
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sys-monitor:latest

      
